openapi: 3.0.0
servers:
  - url: 'https://api.nexmo.com/'
info:
  version: 1.0.0
  title: Subaccounts API
  description: >-
    The Nexmo Subaccounts API enables you to create subaccounts under your primary account. Subaccounts facilitate differential product configuration, reporting, and billing.
paths:
  /accounts/{api_key}/subaccounts:
    post:
      summary: Create subaccount
      operationId: createSubAccount
      description: >
        Create a subaccount for a given primary account.
      tags: 
        - Subaccount Management
      parameters:
        - name: api_key
          in: path
          description: ID of the primary account
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewSubaccountRequest'
      responses:
        '200':
          description: Subaccount response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubaccountCreateResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalError'
    get:
      summary: Retrieve list of subaccounts
      operationId: retrieveSubaccountsList
      description: >
        Get the information of all the subaccounts owned by the primary account.
      tags: 
        - Subaccount Management
      parameters:
        - name: api_key
          in: path
          description: ID of the primary account
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Subaccounts response
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/SubaccountsAllResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalError'
  /accounts/{api_key}/subaccounts/{subaccount_key}:
    get:
      summary: Retrieve a subaccount
      operationId: retrieveSubaccount
      description: >
        Get the information of a subaccount specified with its API key.
      tags: 
        - Subaccount Management
      parameters:
        - name: api_key
          in: path
          description: ID of the primary account
          required: true
          schema:
            type: string
        - name: subaccount_key
          in: path
          description: ID of the subaccount
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Subaccount response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubaccountInfoResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalError'
    patch:
      summary: Modify a subaccount
      operationId: modifySubaccount
      description: >
        Change one or more properties of a subaccount.
      tags: 
        - Subaccount Management
      parameters:
        - name: api_key
          in: path
          description: ID of the primary account
          required: true
          schema:
            type: string
        - name: subaccount_key
          in: path
          description: ID of the subaccount
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModifySubaccountRequest'
      responses:
        '200':
          description: Subaccount response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubaccountInfoResponse'
        '400':
          $ref: '#/components/responses/BadRequestError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '422':
          $ref: '#/components/responses/UnprocessableEntityError'
        '500':
          $ref: '#/components/responses/InternalError'
  /accounts/{api_key}/credit-transfers:
    post:
      summary: Transfer credit
      operationId: transferCredit
      description: >
        Transfer credit limit between a primary account and one of its subaccounts.
      tags: 
        - Transfers
      parameters:
        - name: api_key
          in: path
          description: ID of the primary account
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferBalanceOrCreditRequest'
      responses:
        '200':
          description: Credit transfer response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferCreditResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '422':
          $ref: '#/components/responses/UnprocessableEntityError'
        '500':
          $ref: '#/components/responses/InternalError'
    get:
      summary: Retrieve list of credit transfers
      operationId: retrieveCreditTransfers
      description: >
        Retrieve a list of credit transfers that have taken place for a primary account within a specified time period.
      tags: 
        - Transfers
      parameters:
        - name: api_key
          in: path
          description: ID of the primary account.
          required: true
          schema:
            type: string
        - name: start_date
          in: query
          description: Start of the retrieval period.
          required: true
          schema:
            type: string
        - name: end_date
          in: query
          description: End of the retrieval period. If absent then all transfers until now is returned.
          required: false
          schema:
            type: string
        - name: subaccount
          in: query
          description: List of subaccounts.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List credit transfers response
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ListCreditTransfersResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalError'
  /accounts/{api_key}/balance-transfers:
    post:
      summary: Transfer balance
      description: >
        Transfer positive balance between a primary account and one of its subaccounts.
        Note that this will only work if the source account has a positive balance!
      tags: 
        - Transfers
      operationId: transferBalance
      parameters:
        - name: api_key
          in: path
          description: ID of the primary account
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferBalanceOrCreditRequest'
      responses:
        '200':
          description: Balance transfer response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransferBalanceResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '422':
          $ref: '#/components/responses/UnprocessableEntityError'
        '500':
          $ref: '#/components/responses/InternalError'
    get:
      summary: Retrieve list of balance transfers
      operationId: retrieveBalanceTransfers
      description: >
        Retrieve a list of balance transfers that have taken place for a primary account within a specified time period.
      tags: 
        - Transfers
      parameters:
        - name: api_key
          in: path
          description: ID of the primary account.
          required: true
          schema:
            type: string
        - name: start_date
          in: query
          description: Start of the retrieval period.
          required: true
          schema:
            type: string
        - name: end_date
          in: query
          description: End of the retrieval period. If absent then all transfers until now is returned.
          required: false
          schema:
            type: string
        - name: subaccount
          in: query
          description: List of subaccounts.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: List balance transfers response
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/ListBalanceTransfersResponse'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '404':
          $ref: '#/components/responses/NotFoundError'
        '500':
          $ref: '#/components/responses/InternalError'
tags:
  - name: Subaccount Management
    description: This section shows how you can create, retrieve and modify subaccounts of a primary account.
  - name: Transfers
    description: This section shows how you execute credit and balance transfers, as well as viewing past transactions.
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    basicAuth:
      type: http
      scheme: basic
  responses:
    UnauthorizedError:
      description: Credential is missing or invalid
      content:
        application/json:
          schema:
            type: object
            required:
              - type
              - title
              - detail
              - instance
            properties:
              type:
                type: string
                example: 'https://developer.nexmo.com/api-errors#unauthorized'
              title:
                type: string
                example: 'Invalid credentials supplied'
              detail:
                type: string
                example: 'You did not provide correct credentials'
              instance:
                type: string
                example: '798b8f199c45014ab7b08bfe9cc1c12c'
    ForbiddenError:
      description: Action is forbidden
      content:
        application/json:
          schema:
            type: object
            required:
              - type
              - title
              - detail
              - instance
            properties:
              type:
                type: string
                example: 'https://developer.nexmo.com/api-errors#unprovisioned'
              title:
                type: string
                example: 'Authorisation error'
              detail:
                type: string
                example: 'Account acc6111f is not provisioned to access Subaccount Provisioning API'
              instance:
                type: string
                example: '158b8f199c45014ab7b08bfe9cc1c12c'
    NotFoundError:
      description: The account ID provided does not exist in our system or you do not have access
      content:
        application/json:
          schema:
            type: object
            required:
              - type
              - title
              - detail
              - instance
            properties:
              type:
                type: string
                example: 'https://developer.nexmo.com/api-errors#invalid-api-key'
              title:
                type: string
                example: 'Invalid API Key'
              detail:
                type: string
                example: "API key 'acc6111f' does not exist, or you do not have access"
              instance:
                type: string
                example: '158b8f199c45014ab7b08bfe9cc1c12c'
    BadRequestError:
      description: Bad Request Error
      content:
        application/json:
          schema:
            type: object
            required:
              - type
              - title
              - detail
              - instance
            properties:
              type:
                type: string
                example: 'https://developer.nexmo.com/api-errors/account/subaccounts#validation'
              title:
                type: string
                example: 'Bad Request'
              detail:
                type: string
                example: 'The request failed due to validation errors'
              invalid_parameters:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: 'name'
                    reason:
                      type: string
                      example: 'Does not meet length requirements'
              instance:
                type: string
                example: '158b8f199c45014ab7b08bfe9cc1c12c'
    UnprocessableEntityError:
      description: Validation Error
      content:
        application/json:
          schema:
            type: object
            required:
              - type
              - title
              - detail
              - invalid_parameters
              - instance
            properties:
              type:
                type: string
                example: 'https://developer.nexmo.com/api-errors/account/subaccounts#validation'
              title:
                type: string
                example: 'Bad Request'
              detail:
                type: string
                example: 'The request failed due to validation errors'
              invalid_parameters:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                      example: 'use_primary_account_balance'
                    reason:
                      type: string
                      example: "Should be either 'true' or 'false'"
              instance:
                type: string
                example: '158b8f199c45014ab7b08bfe9cc1c12c'
    InternalError:
      description: An internal error has occurred
      content:
        application/json:
          schema:
            type: object
            required:
              - type
              - title
              - detail
              - instance
            properties:
              type:
                type: string
                example: 'https://developer.nexmo.com/api-errors#internal-error'
              title:
                type: string
                example: 'Internal Error'
              detail:
                type: string
                example: 'An internal error occurred. Please try again shortly'
              instance:
                type: string
                example: '158b8f199c45014ab7b08bfe9cc1c12c'
  schemas:
    SubaccountsAllResponse:
      properties:
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  example: "/accounts/acc6111f/subaccounts"
          example:
            self:
              href: '/accounts/acc6111f/subaccounts'
        _embedded:
          type: array
          items:
              type: object
              properties:
                _links:
                  type: object
                  properties:
                    self:
                      type: object
                      properties:
                        href:
                          type: string
                          example: "/accounts/acc6111f/subaccounts/bbe6222f"
                  example:
                    self:
                      href: '/accounts/acc6111f/subaccounts/bbe6222f'
                api_key:
                  example: "bbe6222f"
                  type: string
                  description: >-
                    Unique subaccount ID
                name:
                  type: string
                  example: 'Subaccount department A'
                  description: >-
                   Name of the subaccount
                primary_account_api_key:
                  example: 'acc6111f'
                  type: string
                  description: >-
                    Unique primary account ID
                use_primary_account_balance:
                  example: true
                  type: boolean
                  description: >-
                    Flag showing if balance is shared with primary account
                created_at:
                  example: '2018-03-02T16:34:49Z'
                  type: string
                  description: >-
                    Subaccount creation date and time
                suspended:
                  example: false
                  type: boolean
                  description: >-
                    Subaccount status
    SubaccountCreateResponse:
      properties:
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  example: "/accounts/acc6111f/subaccounts/bbe6222f"
          example:
            self:
              href: '/accounts/acc6111f/subaccounts/bbe6222f'
        api_key:
          example: 'bbe6222f'
          type: string
          description: >-
            Unique subaccount ID.
        name:
          type: string
          example: 'Subaccount department A'
          description: >-
           Name of the subaccount.
        secret:
          type: string
          example: 'Password123'
          description: >-
           API secret of the subaccount.
        primary_account_api_key:
          example: 'acc6111f'
          type: string
          description: >-
            Unique primary account ID.
        use_primary_account_balance:
          example: true
          type: boolean
          description: >-
            Flag showing if balance is shared with primary account.
        balance:
          example: 100.25
          type: number
          description: >-
            Balance of the subAccount. Value is null if balance is shared with primary account.
        credit_limit:
          example: -100.25
          type: number
          description: >-
            Credit limit of the subAccount. Value is null if balance is shared with primary account.
        created_at:
          example: '2018-03-02T16:34:49Z'
          type: string
          description: >-
            Subaccount creation date and time.
        suspended:
          example: false
          type: boolean
          description: >-
            Subaccount suspension status.
      example:
        _links:
          self:
            href: '/accounts/acc6111f/subaccounts/bbe6222f'
        api_key: 'bbe6222f'
        name: 'Subaccount department A'
        secret: 'Pasword123'
        primary_account_api_key: 'acc6111f'
        use_primary_account_balance: true
        created_at: '2018-03-02T16:34:49Z'
        suspended: false
    SubaccountInfoResponse:
      properties:
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  example: "/accounts/acc6111f/subaccounts/bbe6222f"
          example:
            self:
              href: '/accounts/acc6111f/subaccounts/bbe6222f'
        api_key:
          example: 'bbe6222f'
          type: string
          description: >-
            Unique subaccount ID.
        name:
          type: string
          example: 'Subaccount department A'
          description: >-
           Name of the subaccount.
        primary_account_api_key:
          example: 'acc6111f'
          type: string
          description: >-
            Unique primary account ID.
        use_primary_account_balance:
          example: true
          type: boolean
          description: >-
            Flag showing if balance is shared with primary account.
        balance:
          example: 100.25
          type: number
          description: >-
            Balance of the subAccount. Value is null if balance is shared with primary account.
        credit_limit:
          example: -100.25
          type: number
          description: >-
            Credit limit of the subAccount. Value is null if balance is shared with primary account.
        created_at:
          example: '2018-03-02T16:34:49Z'
          type: string
          description: >-
            Subaccount creation date and time.
        suspended:
          example: false
          type: boolean
          description: >-
            Subaccount suspension status.
      example:
        _links:
          self:
            href: '/accounts/acc6111f/subaccounts/bbe6222f'
        api_key: 'bbe6222f'
        name: 'Subaccount department A'
        secret: 'Pasword123'
        primary_account_api_key: 'acc6111f'
        use_primary_account_balance: true
        created_at: '2018-03-02T16:34:49Z'
        suspended: false
    TransferCreditResponse:
      properties:
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  example: '/accounts/acc6111f/credit-transfers/07b5-46e1-a527-85530e625800'
          example:
            self:
              href: '/accounts/acc6111f/credit-transfers/07b5-46e1-a527-85530e625800'
        credit_transfer_id:
          example: '07b5-46e1-a527-85530e625800'
          type: string
          description: >-
            Unique credit transfer ID
        amount:
          example: 123.45
          type: number
          description: >-
            Credit transfer amount
        from:
          example: '7c9738e6'
          type: string
          description: >-
            Account the credit is transferred from
        to:
          example: 'ad6dc56f'
          type: string
          description: >-
            Account the credit is transferred to
        reference:
          example: 'This gets added to the audit log'
          type: string
          description: >-
            Reference for the credit transfer
        created_at:
          example: '2019-03-02T16:34:49Z'
          type: string
          description: >-
            The date and time when the credit transfer was executed
      example:
        _links:
          self:
            href: '/accounts/acc6111f/credit-transfers/07b5-46e1-a527-85530e625800'
        credit_transfer_id: '07b5-46e1-a527-85530e625800'
        amount: 123.45
        from: '7c9738e6'
        to: 'ad6dc56f'
        reference: 'This gets added to the audit log'
        created_at: '2019-03-02T16:34:49Z'
    TransferBalanceResponse:
      properties:
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  example: '/accounts/acc6111f/balance-transfers/07b5-46e1-a527-85530e625800'
          example:
            self:
              href: '/accounts/acc6111f/balance-transfers/07b5-46e1-a527-85530e625800'
        balance_transfer_id:
          example: '07b5-46e1-a527-85530e625800'
          type: string
          description: >-
            Unique balance transfer ID
        amount:
          example: 123.45
          type: number
          description: >-
            Balance transfer amount
        from:
          example: '7c9738e6'
          type: string
          description: >-
            Account the balance is transferred from
        to:
          example: 'ad6dc56f'
          type: string
          description: >-
            Account the balance is transferred to
        reference:
          example: 'This gets added to the audit log'
          type: string
          description: >-
            Reference for the balance transfer
        created_at:
          example: '2019-03-02T16:34:49Z'
          type: string
          description: >-
            The date and time when the balance transfer was executed
      example:
        _links:
          self:
            href: '/accounts/acc6111f/balance-transfers/07b5-46e1-a527-85530e625800'
        balance_transfer_id: '07b5-46e1-a527-85530e625800'
        amount: 123.45
        from: '7c9738e6'
        to: 'ad6dc56f'
        reference: 'This gets added to the audit log'
        created_at: '2019-03-02T16:34:49Z'
    ListCreditTransfersResponse:
      properties:
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  example: '/accounts/acc6111f/credit-transfers'
          example:
            self:
              href: '/accounts/acc6111f/credit-transfers'
        _embedded:
          type: array
          items:
              type: object
              properties:
                _links:
                  type: object
                  properties:
                    self:
                      type: object
                      properties:
                        href:
                          type: string
                          example: '/accounts/acc6111f/credit-transfers/07b5-46e1-a527-85530e625800'
                  example:
                    self:
                      href: '/accounts/acc6111f/credit-transfers/07b5-46e1-a527-85530e625800'
                credit_transfer_id:
                  example: '07b5-46e1-a527-85530e625800'
                  type: string
                  description: >-
                    Unique credit transfer ID
                amount:
                  example: 123.45
                  type: number
                  description: >-
                    Credit transfer amount
                from:
                  example: '7c9738e6'
                  type: string
                  description: >-
                    Account the credit is transferred from
                to:
                  example: 'ad6dc56f'
                  type: string
                  description: >-
                    Account the credit is transferred to
                reference:
                  example: 'This gets added to the audit log'
                  type: string
                  description: >-
                    Reference for the credit transfer
                created_at:
                  example: '2019-03-02T16:34:49Z'
                  type: string
                  description: >-
                    The date and time when the credit transfer was executed
    ListBalanceTransfersResponse:
      properties:
        _links:
          type: object
          properties:
            self:
              type: object
              properties:
                href:
                  type: string
                  example: '/accounts/acc6111f/balance-transfers'
          example:
            self:
              href: '/accounts/acc6111f/balance-transfers'
        _embedded:
          type: array
          items:
              type: object
              properties:
                _links:
                  type: object
                  properties:
                    self:
                      type: object
                      properties:
                        href:
                          type: string
                          example: '/accounts/acc6111f/balance-transfers/07b5-46e1-a527-85530e625800'
                  example:
                    self:
                      href: '/accounts/acc6111f/balance-transfers/07b5-46e1-a527-85530e625800'
                balance_transfer_id:
                  example: '07b5-46e1-a527-85530e625800'
                  type: string
                  description: >-
                    Unique balance transfer ID
                amount:
                  example: 123.45
                  type: number
                  description: >-
                    Balance transfer amount
                from:
                  example: '7c9738e6'
                  type: string
                  description: >-
                    Account the balance is transferred from
                to:
                  example: 'ad6dc56f'
                  type: string
                  description: >-
                    Account the balance is transferred to
                reference:
                  example: 'This gets added to the audit log'
                  type: string
                  description: >-
                    Reference for the balance transfer
                created_at:
                  example: '2019-03-02T16:34:49Z'
                  type: string
                  description: >-
                    The date and time when the balance transfer was executed
    NewSubaccountRequest:
      type: object
      properties:
        name:
          type: string
          example: 'Subaccount department A'
        secret:
          type: string
          example: 'Password123'
        use_primary_account_balance:
          type: boolean
          example: false
      required:
        - name
    ModifySubaccountRequest:
      type: object
      properties:
        name:
          type: string
          example: 'Subaccount department A'
        suspended:
          type: boolean
          example: true
        use_primary_account_balance:
          type: boolean
          example: false
    TransferBalanceOrCreditRequest:
      type: object
      properties:
        from:
          type: string
          example: '7c9738e6'
        to:
          type: string
          example: 'ad6dc56f'
        amount:
          type: number
          example: '123.45'
        reference:
          type: string
          example: 'This gets added to the audit log'
      required:
        - from
        - to
        - amount